version: "3.8"

services:
  backend:
    image: khoadeptraivai/traffic-law-backend:v1
    container_name: traffic-law-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/backend
      - API_VERSION=${API_VERSION:-v0}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4.1-mini}
      - RERANKER_MODEL=${RERANKER_MODEL:-gpt-4.1-mini}
      - HYBRID_SEARCH_TOP_K=${HYBRID_SEARCH_TOP_K:-40}
      - RERANK_TOP_K=${RERANK_TOP_K:-5}
      - DENSE_MODEL_NAME=${DENSE_MODEL_NAME:-jinaai/jina-embeddings-v3}
      - SPARSE_MODEL_NAME=${SPARSE_MODEL_NAME:-Qdrant/bm25}
    volumes:
       - ./backend:/app/backend
    networks:
      - traffic-law-network

networks:
  traffic-law-network:
    driver: bridge